name: NinoBot
description: A starting point for Dart libraries or applications.
# version: 1.0.0
# homepage: https://www.example.com
# author: Pedro <pedroeugeniocavalcanti@gmail.com>

environment:
  sdk: '>=2.4.0 <3.0.0'

dependencies:
  nyxx: '>=0.30.0'
  intl: '^0.15.8'